package com.hnp.filemanagement;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.regex.Pattern;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Keeps the interface self-contained: no runtime asset may come from the internet, and none may
 * depend on Maven resolving a WebJar. Both failure modes reach the browser as an unstyled page
 * with "Uncaught SyntaxError: Unexpected token '<'", because a 404 for a script is served as HTML.
 */
class UiResourceTest {

    private static final Path RESOURCES = Path.of("src", "main", "resources");
    private static final Path TEMPLATES = RESOURCES.resolve("templates");
    private static final Path VENDOR = RESOURCES.resolve("static/vendor");

    private static final Pattern EXTERNAL_ASSET = Pattern.compile(
            "(?:src|href)\\s*=\\s*[\\\"'](?:https?:)?//|url\\(\\s*[\\\"']?(?:https?:)?//",
            Pattern.CASE_INSENSITIVE);

    @Test
    void allTemplatesDeclarePersianRightToLeftLayout() throws IOException {
        for (Path template : htmlFiles(TEMPLATES)) {
            String source = Files.readString(template);
            assertTrue(source.contains("lang=\"fa\""), () -> template + " must declare lang=fa");
            assertTrue(source.contains("dir=\"rtl\""), () -> template + " must declare dir=rtl");
        }
    }

    @Test
    void userFacingTemplatesUseSharedOfflineAssets() throws IOException {
        for (Path template : htmlFiles(TEMPLATES)) {
            String fileName = template.getFileName().toString();
            if (fileName.equals("fragments.html") || fileName.equals("navbar.html")) {
                continue;
            }

            String source = Files.readString(template);
            assertTrue(source.contains("fragments.html :: head-assets"),
                    () -> template + " must use the shared head assets");
            assertTrue(source.contains("fragments.html :: scripts"),
                    () -> template + " must use the shared scripts");
            assertFalse(EXTERNAL_ASSET.matcher(source).find(),
                    () -> template + " must not load runtime assets from the internet");
        }
    }

    /**
     * A WebJar URL means the asset only exists if Maven resolved that artifact. The UI assets are
     * vendored under static/vendor/ precisely so that cannot fail; nothing may go back.
     */
    @Test
    void noTemplateLoadsAnAssetFromAWebJar() throws IOException {
        for (Path template : htmlFiles(TEMPLATES)) {
            assertFalse(Files.readString(template).contains("/webjars/"),
                    () -> template + " loads a WebJar; vendor the asset under static/vendor instead");
        }
    }

    @Test
    void everyVendoredAssetIsPresentAndNonEmpty() throws IOException {
        List<String> required = List.of(
                "alpine/alpine.min.js",
                "jquery/jquery.min.js",
                "select2/select2.min.js",
                "select2/select2.min.css",
                "bootstrap-icons/bootstrap-icons.min.css",
                "bootstrap-icons/fonts/bootstrap-icons.woff2");

        for (String name : required) {
            Path asset = VENDOR.resolve(name);
            assertTrue(Files.exists(asset), () -> "missing vendored asset: " + asset);
            assertThat(Files.size(asset)).as("%s looks truncated", asset).isGreaterThan(1_000L);
        }

        assertTrue(Files.exists(VENDOR.resolve("README.md")),
                "vendored assets must record their versions and licences");
    }

    @Test
    void sharedFragmentsLoadEveryUiAssetFromTheSourceTree() throws IOException {
        String fragments = Files.readString(TEMPLATES.resolve("fragments.html"));

        assertTrue(fragments.contains("/css/app.css"), "the compiled Tailwind stylesheet");
        assertTrue(fragments.contains("/vendor/bootstrap-icons/bootstrap-icons.min.css"));
        assertTrue(fragments.contains("/vendor/alpine/alpine.min.js"));
        assertTrue(fragments.contains("/vendor/jquery/jquery.min.js"));
        assertTrue(fragments.contains("/vendor/select2/select2.min.css"));
        assertTrue(fragments.contains("/vendor/select2/select2.min.js"));
        assertFalse(fragments.contains("bootstrap.bundle"), "Bootstrap JS was replaced by Alpine");
        assertFalse(fragments.contains("bootstrap.rtl"), "Bootstrap CSS was replaced by Tailwind");
    }

    /**
     * The stylesheet is generated by the Tailwind CLI and committed, so `./mvnw package` needs no
     * Node. If the compiled file goes missing the whole UI loses its styling silently.
     */
    @Test
    void compiledStylesheetIsCommittedAndBuiltFromTheTailwindSource() throws IOException {
        Path source = Path.of("src", "main", "frontend", "app.css");
        Path compiled = RESOURCES.resolve("static/css/app.css");

        assertTrue(Files.exists(source), "Tailwind source must be committed");
        assertTrue(Files.readString(source).contains("@import \"tailwindcss\""));
        assertThat(Files.size(compiled)).as("compiled stylesheet looks empty").isGreaterThan(10_000L);
        assertTrue(Files.readString(compiled).contains("Vazirmatn-Variable.woff2"),
                "the local font must survive the build");
    }

    @Test
    void nothingInTheBuildRequiresNode() throws IOException {
        String pom = Files.readString(Path.of("pom.xml"));

        assertFalse(pom.contains("frontend-maven-plugin"),
                "the Maven build must not download or run Node");
        assertFalse(pom.contains("exec-maven-plugin"),
                "the Maven build must not shell out to npm");
    }

    @Test
    void localFontAndThemeArePackaged() throws IOException {
        Path font = RESOURCES.resolve("static/css/fonts/vazirmatn/Vazirmatn-Variable.woff2");
        Path license = RESOURCES.resolve("static/css/fonts/vazirmatn/OFL.txt");

        assertThat(Files.size(font)).isGreaterThan(100_000L);
        assertTrue(Files.readString(license).contains("SIL OPEN FONT LICENSE Version 1.1"));
    }

    @Test
    void uiDocumentationIsWrittenInEnglish() throws IOException {
        String guide = Files.readString(Path.of("docs", "ui.md"));
        assertFalse(Pattern.compile("[\\u0600-\\u06ff]").matcher(guide).find());
    }

    private List<Path> htmlFiles(Path root) throws IOException {
        try (var files = Files.walk(root)) {
            return files.filter(path -> path.getFileName().toString().endsWith(".html")).toList();
        }
    }
}
