package com.hnp.filemanagement.file.domain;

import com.hnp.filemanagement.shared.exception.InvalidDataException;

import java.util.Arrays;
import java.util.List;
import java.util.regex.Pattern;

/**
 * An object key taken apart (roadmap 9.3).
 *
 * <p>The key space is the folder tree flattened with {@code /}, exactly as S3 flattens its own —
 * there are no folders in a key, only separators. Two shapes exist and they are told apart
 * structurally, not by a parameter:
 *
 * <pre>
 *   folders…/{fileName}/v{n}/{fileName}.{ext}   a stored object: read, deleted, listed
 *   folders…/{fileName}/{fileName}.{ext}        a write: "the next version of this file"
 * </pre>
 *
 * <p><b>The folder part is a list, not a fixed pair.</b> Today it is always sub-category then tag,
 * because the taxonomy is three levels deep. Roadmap Phase 7 makes it any depth, and nothing here
 * has to change for that — which is why this parses from the end rather than counting from the
 * start.
 *
 * @param folders  the folder names between the bucket and the file, outermost first
 * @param fileName the logical file, which is also a folder in the key
 * @param version  the version, or null for the write shape
 * @param objectName the stored file name including its extension
 */
public record ObjectKeyDTO(List<String> folders, String fileName, Integer version, String objectName) {

    private static final Pattern VERSION = Pattern.compile("v([0-9]+)");

    /** The write shape: no version, so the server chooses the next one. */
    public boolean isVersionless() {
        return version == null;
    }

    public String extension() {
        int dot = objectName.lastIndexOf('.');
        if (dot < 0 || dot == objectName.length() - 1) {
            throw new InvalidDataException("object name has no extension: " + objectName);
        }
        return objectName.substring(dot + 1);
    }

    /** The canonical key of a stored object, which is what a listing returns and a GET takes. */
    public static String of(List<String> folders, String fileName, int version, String objectName) {
        return String.join("/", folders) + (folders.isEmpty() ? "" : "/")
                + fileName + "/v" + version + "/" + objectName;
    }

    /**
     * Parses a key, or refuses it.
     *
     * <p>Refused rather than guessed at: a key is generated by this application and echoed back by a
     * client, so one that does not fit either shape is a caller error, and answering "not found"
     * would send them looking for a document instead of at their own string.
     */
    public static ObjectKeyDTO parse(String key) {
        if (key == null || key.isBlank()) {
            throw new InvalidDataException("empty object key");
        }
        List<String> parts = Arrays.stream(key.split("/")).filter(part -> !part.isBlank()).toList();
        if (parts.size() < 2) {
            throw new InvalidDataException("object key is too short: " + key);
        }

        String objectName = parts.getLast();
        String maybeVersion = parts.get(parts.size() - 2);

        var matcher = VERSION.matcher(maybeVersion);
        if (matcher.matches()) {
            if (parts.size() < 3) {
                throw new InvalidDataException("object key names a version but no file: " + key);
            }
            return new ObjectKeyDTO(parts.subList(0, parts.size() - 3),
                    parts.get(parts.size() - 3), Integer.valueOf(matcher.group(1)), objectName);
        }
        return new ObjectKeyDTO(parts.subList(0, parts.size() - 2), maybeVersion, null, objectName);
    }
}
