-- PostgreSQL baseline (roadmap 3.4, release B): the whole schema as the MySQL migrations V1.0 to
-- V2.19 leave it, written once in PostgreSQL's own terms. On PostgreSQL this file is the only
-- migration that has ever run; the MySQL history (db/migration/mysql) never runs here.
--
-- docs/schema.md is the specification, and two tests hold this file to it:
--   * ddl-auto=validate, at every start, for the tables, columns and types the entities map;
--   * SchemaParityTest, which migrates a MySQL and a PostgreSQL side by side and compares every
--     table, column, nullability, default, key, foreign key and index by name - what validate
--     does not look at, and what a forgotten unique index would otherwise let through silently.
--
-- What is deliberately different from MySQL, and why:
--
--   * DATETIME is TIMESTAMP(0). MySQL's DATETIME keeps no fraction of a second; a bare TIMESTAMP
--     would keep microseconds, and a value written and read back would no longer be the value
--     the other database gives back. Without time zone, as DATETIME is (TIMESTAMPTZ is issue 24,
--     a later V3.x).
--   * TINYINT(1) is BOOLEAN - the one such column, content_kind.text_only.
--   * AUTO_INCREMENT is GENERATED BY DEFAULT AS IDENTITY: BY DEFAULT, so that the data copy can
--     insert the ids MySQL gave (they are written down outside these tables - storage keys, the
--     audit trail, the PL/SQL clients) and then move each sequence past them.
--   * A name MySQL compared without case through its utf8mb4_unicode_ci collation has a unique
--     index on upper(column) here, under the constraint's own name - the expression the queries
--     compare with since release A (issue 86). Tokens, keys, paths and the code-written
--     extensions stay exact, as on MySQL they only happen to be case-insensitive.
--   * The index on folder.path is varchar_pattern_ops: every subtree and folder-access query is a
--     prefix LIKE, which a B-tree under a linguistic collation cannot serve.
--   * MySQL indexes every foreign key column by itself, naming the index after the constraint
--     where no other index already starts with that column. PostgreSQL does not, so those indexes
--     are declared here under the same names: a delete that checks the rows pointing at it, and
--     every lookup by a foreign key, find the same index on either database.
--   * ENGINE, CHARSET and COLLATE clauses have no equivalent: the database is created
--     ENCODING 'UTF8' with a UTF-8 LC_CTYPE (under C, upper() would fold ASCII only). The ascii
--     and utf8mb4_bin columns of MySQL (ids, checksums, paths, the search keys) are plain
--     VARCHAR: PostgreSQL compares every VARCHAR exactly, which is what those were declared for.
--
-- The seed rows at the end are what the MySQL migrations leave in an empty database, so that an
-- empty PostgreSQL boots to the same application an empty MySQL does. The permissions, the fixed
-- roles and the first administrator are not among them: DataInitializer writes those at every
-- start, on either database.

-- ------------------------------------------------------------------ the database itself
-- Refused before anything is created, rather than found out later: every case-insensitive name
-- below rests on upper(), and upper() folds only ASCII in a database created with LC_CTYPE 'C' or
-- POSIX - 'É' and 'é' would then be two names, and the unique indexes would not say so. The
-- check is on what upper() does, not on the locale's name, which differs between Linux
-- ('en_US.utf8') and Windows ('English_United States.utf8', or an ICU provider).
-- docs/deployment.md creates the database the way this expects.
DO
$$
BEGIN
    IF current_setting('server_encoding') <> 'UTF8' THEN
        RAISE EXCEPTION 'this database is encoded %, not UTF8: create it with ENCODING ''UTF8''',
            current_setting('server_encoding');
    END IF;
    IF upper('é') <> 'É' THEN
        RAISE EXCEPTION 'this database''s LC_CTYPE (%) folds ASCII only: create it with a UTF-8 locale (docs/deployment.md)',
            (SELECT datctype FROM pg_database WHERE datname = current_database());
    END IF;
END
$$;

-- ------------------------------------------------------------------ accounts and permissions

CREATE TABLE app_user
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(150) NOT NULL,
    personel_code INTEGER      NOT NULL,
    national_code VARCHAR(10)  NOT NULL,
    email         VARCHAR(150),
    phone_number  VARCHAR(15),
    password      VARCHAR(100) NOT NULL,
    first_name    VARCHAR(250) NOT NULL,
    last_name     VARCHAR(250) NOT NULL,
    created_at    TIMESTAMP(0) NOT NULL,
    updated_at    TIMESTAMP(0),
    login_type    INTEGER      NOT NULL DEFAULT 0,
    enabled       INTEGER      NOT NULL,
    state         INTEGER      NOT NULL,
    CONSTRAINT uq_user_national_code UNIQUE (national_code),
    CONSTRAINT uq_user_personel_code UNIQUE (personel_code),
    CONSTRAINT uq_user_phone_number UNIQUE (phone_number)
);
CREATE UNIQUE INDEX uq_user_username ON app_user (upper(username));
CREATE UNIQUE INDEX uq_user_email ON app_user (upper(email));
CREATE INDEX ix_user_created_at ON app_user (created_at);

CREATE TABLE role
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(100) NOT NULL
);
CREATE UNIQUE INDEX uq_role_role_name ON role (upper(role_name));

CREATE TABLE permission
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_name VARCHAR(100) NOT NULL,
    description     VARCHAR(1500),
    CONSTRAINT uq_permission_permission UNIQUE (permission_name)
);

CREATE TABLE permission_role
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       INTEGER NOT NULL,
    permission_id INTEGER NOT NULL,
    CONSTRAINT uq_permission_role UNIQUE (role_id, permission_id),
    CONSTRAINT fk_permission_role_permission_id FOREIGN KEY (permission_id) REFERENCES permission (id),
    CONSTRAINT fk_permission_role_role_id FOREIGN KEY (role_id) REFERENCES role (id)
);
CREATE INDEX fk_permission_role_permission_id ON permission_role (permission_id);

CREATE TABLE user_role
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_user_role_role_id FOREIGN KEY (role_id) REFERENCES role (id),
    CONSTRAINT fk_user_role_user_id FOREIGN KEY (user_id) REFERENCES app_user (id)
);
CREATE INDEX fk_user_role_role_id ON user_role (role_id);

-- ------------------------------------------------------------------ the tree and its tags

CREATE TABLE tag_group
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,
    title      VARCHAR(200) NOT NULL,
    enabled    INTEGER      NOT NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0),
    created_by INTEGER,
    updated_by INTEGER,
    CONSTRAINT fk_tag_group_created_by_user FOREIGN KEY (created_by) REFERENCES app_user (id),
    CONSTRAINT fk_tag_group_updated_by_user FOREIGN KEY (updated_by) REFERENCES app_user (id)
);
CREATE UNIQUE INDEX uq_tag_group_name ON tag_group (upper(name));
CREATE INDEX fk_tag_group_created_by_user ON tag_group (created_by);
CREATE INDEX fk_tag_group_updated_by_user ON tag_group (updated_by);

CREATE TABLE folder
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id           INTEGER,
    name                VARCHAR(100)  NOT NULL,
    search_name         VARCHAR(200)  NOT NULL,
    display_name        VARCHAR(200)  NOT NULL,
    search_display_name VARCHAR(400)  NOT NULL,
    path                VARCHAR(1000) NOT NULL,
    depth               INTEGER       NOT NULL,
    kind                VARCHAR(30)   NOT NULL,
    owner_user_id       INTEGER,
    tag_group_id        INTEGER,
    quota_bytes         BIGINT,
    enabled             INTEGER       NOT NULL,
    state               INTEGER       NOT NULL,
    created_at          TIMESTAMP(0)  NOT NULL,
    updated_at          TIMESTAMP(0),
    created_by          INTEGER,
    updated_by          INTEGER,
    CONSTRAINT uq_folder_owner_user UNIQUE (owner_user_id),
    CONSTRAINT fk_folder_created_by_user FOREIGN KEY (created_by) REFERENCES app_user (id),
    CONSTRAINT fk_folder_owner_user FOREIGN KEY (owner_user_id) REFERENCES app_user (id),
    CONSTRAINT fk_folder_parent FOREIGN KEY (parent_id) REFERENCES folder (id),
    CONSTRAINT fk_folder_tag_group FOREIGN KEY (tag_group_id) REFERENCES tag_group (id),
    CONSTRAINT fk_folder_updated_by_user FOREIGN KEY (updated_by) REFERENCES app_user (id)
);
CREATE UNIQUE INDEX uq_folder_sibling_name ON folder (parent_id, upper(name));
CREATE INDEX ix_folder_parent ON folder (parent_id);
CREATE INDEX ix_folder_path ON folder (path varchar_pattern_ops);
CREATE INDEX fk_folder_created_by_user ON folder (created_by);
CREATE INDEX fk_folder_tag_group ON folder (tag_group_id);
CREATE INDEX fk_folder_updated_by_user ON folder (updated_by);

CREATE TABLE tag
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   INTEGER,
    name       VARCHAR(100) NOT NULL,
    title      VARCHAR(200) NOT NULL,
    enabled    INTEGER      NOT NULL,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0),
    created_by INTEGER,
    updated_by INTEGER,
    CONSTRAINT fk_tag_created_by_user FOREIGN KEY (created_by) REFERENCES app_user (id),
    CONSTRAINT fk_tag_group FOREIGN KEY (group_id) REFERENCES tag_group (id),
    CONSTRAINT fk_tag_updated_by_user FOREIGN KEY (updated_by) REFERENCES app_user (id)
);
CREATE UNIQUE INDEX uq_tag_name_per_group ON tag (group_id, upper(name));
CREATE INDEX fk_tag_created_by_user ON tag (created_by);
CREATE INDEX fk_tag_updated_by_user ON tag (updated_by);

CREATE TABLE role_folder
(
    role_id    INTEGER     NOT NULL,
    folder_id  INTEGER     NOT NULL,
    permission VARCHAR(10) NOT NULL DEFAULT 'READ',
    PRIMARY KEY (role_id, folder_id),
    CONSTRAINT fk_role_folder_folder FOREIGN KEY (folder_id) REFERENCES folder (id) ON DELETE CASCADE,
    CONSTRAINT fk_role_folder_role FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE
);
CREATE INDEX ix_role_folder_role ON role_folder (role_id);
CREATE INDEX fk_role_folder_folder ON role_folder (folder_id);

CREATE TABLE user_folder
(
    user_id    INTEGER     NOT NULL,
    folder_id  INTEGER     NOT NULL,
    permission VARCHAR(10) NOT NULL DEFAULT 'READ',
    PRIMARY KEY (user_id, folder_id),
    CONSTRAINT fk_user_folder_folder FOREIGN KEY (folder_id) REFERENCES folder (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_folder_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);
CREATE INDEX ix_user_folder_user ON user_folder (user_id);
CREATE INDEX fk_user_folder_folder ON user_folder (folder_id);

-- ------------------------------------------------------------------ files

CREATE TABLE file_info
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id           VARCHAR(36)   NOT NULL,
    file_name             VARCHAR(100)  NOT NULL,
    search_name           VARCHAR(200)  NOT NULL,
    code_name             VARCHAR(300)  NOT NULL,
    file_name_description VARCHAR(500)  NOT NULL,
    description           VARCHAR(1000),
    search_description    VARCHAR(2000),
    file_link             VARCHAR(1000),
    last_version          INTEGER       NOT NULL,
    folder_id             INTEGER       NOT NULL,
    enabled               INTEGER       NOT NULL,
    state                 INTEGER       NOT NULL,
    created_at            TIMESTAMP(0)  NOT NULL,
    updated_at            TIMESTAMP(0),
    created_by            INTEGER       NOT NULL,
    updated_by            INTEGER,
    CONSTRAINT uq_file_info_external_id UNIQUE (external_id),
    CONSTRAINT fk_file_info_created_by_user FOREIGN KEY (created_by) REFERENCES app_user (id),
    CONSTRAINT fk_file_info_folder FOREIGN KEY (folder_id) REFERENCES folder (id),
    CONSTRAINT fk_file_info_updated_by_user FOREIGN KEY (updated_by) REFERENCES app_user (id)
);
CREATE UNIQUE INDEX uq_file_info_name_per_folder ON file_info (folder_id, upper(file_name));
CREATE INDEX ix_file_info_created_at ON file_info (created_at);
CREATE INDEX ix_file_info_folder ON file_info (folder_id);
CREATE INDEX ix_file_info_state ON file_info (state);
CREATE INDEX fk_file_info_created_by_user ON file_info (created_by);
CREATE INDEX fk_file_info_updated_by_user ON file_info (updated_by);

CREATE TABLE file_details
(
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_info_id             INTEGER       NOT NULL,
    external_id              VARCHAR(36)   NOT NULL,
    file_name                VARCHAR(100)  NOT NULL,
    search_name              VARCHAR(200)  NOT NULL,
    file_extension           VARCHAR(10)   NOT NULL,
    content_type             VARCHAR(100)  NOT NULL,
    version                  INTEGER       NOT NULL,
    version_name             VARCHAR(100)  NOT NULL,
    version_name_description VARCHAR(1000),
    description              VARCHAR(1000) NOT NULL,
    search_description       VARCHAR(2000) NOT NULL,
    storage_key              VARCHAR(1000) NOT NULL,
    file_link                VARCHAR(1000),
    file_size                BIGINT        NOT NULL,
    checksum_sha256          VARCHAR(64),
    enabled                  INTEGER       NOT NULL,
    state                    INTEGER       NOT NULL,
    created_at               TIMESTAMP(0)  NOT NULL,
    updated_at               TIMESTAMP(0),
    created_by               INTEGER       NOT NULL,
    updated_by               INTEGER,
    CONSTRAINT uq_file_details_external_id UNIQUE (external_id),
    CONSTRAINT fk_file_details_created_by_user FOREIGN KEY (created_by) REFERENCES app_user (id),
    CONSTRAINT fk_file_details_file_info_id FOREIGN KEY (file_info_id) REFERENCES file_info (id),
    CONSTRAINT fk_file_details_updated_by_user FOREIGN KEY (updated_by) REFERENCES app_user (id)
);
CREATE UNIQUE INDEX uq_file_details_version_format ON file_details (file_info_id, version, upper(file_extension));
CREATE INDEX ix_file_details_file_info_version ON file_details (file_info_id, version);
CREATE INDEX ix_file_details_state ON file_details (state);
CREATE INDEX fk_file_details_created_by_user ON file_details (created_by);
CREATE INDEX fk_file_details_updated_by_user ON file_details (updated_by);

CREATE TABLE file_tag
(
    file_info_id INTEGER NOT NULL,
    tag_id       INTEGER NOT NULL,
    PRIMARY KEY (file_info_id, tag_id),
    CONSTRAINT fk_file_tag_file_info FOREIGN KEY (file_info_id) REFERENCES file_info (id),
    CONSTRAINT fk_file_tag_tag FOREIGN KEY (tag_id) REFERENCES tag (id)
);
CREATE INDEX ix_file_tag_tag ON file_tag (tag_id);

CREATE TABLE file_share_link
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash      VARCHAR(64)  NOT NULL,
    file_details_id INTEGER      NOT NULL,
    expires_at      TIMESTAMP(0) NOT NULL,
    password_hash   VARCHAR(100),
    max_downloads   INTEGER,
    download_count  INTEGER      NOT NULL DEFAULT 0,
    failed_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until    TIMESTAMP(0),
    revoked_at      TIMESTAMP(0),
    created_at      TIMESTAMP(0) NOT NULL,
    created_by      INTEGER      NOT NULL,
    CONSTRAINT uq_file_share_link_token UNIQUE (token_hash),
    CONSTRAINT fk_file_share_link_created_by_user FOREIGN KEY (created_by) REFERENCES app_user (id),
    CONSTRAINT fk_file_share_link_file_details FOREIGN KEY (file_details_id) REFERENCES file_details (id) ON DELETE CASCADE
);
CREATE INDEX ix_file_share_link_created_by ON file_share_link (created_by);
CREATE INDEX ix_file_share_link_file_details ON file_share_link (file_details_id);

CREATE TABLE file_storage_write
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key VARCHAR(1000) NOT NULL,
    created_at  TIMESTAMP(0)  NOT NULL
);
CREATE INDEX ix_file_storage_write_created_at ON file_storage_write (created_at);

-- ------------------------------------------------------------------ settings, kinds, upload policy

CREATE TABLE app_setting
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key   VARCHAR(100) NOT NULL,
    setting_value VARCHAR(500) NOT NULL,
    updated_at    TIMESTAMP(0),
    updated_by    INTEGER,
    CONSTRAINT uq_app_setting_key UNIQUE (setting_key),
    CONSTRAINT fk_app_setting_updated_by_user FOREIGN KEY (updated_by) REFERENCES app_user (id)
);
CREATE INDEX fk_app_setting_updated_by_user ON app_setting (updated_by);

CREATE TABLE content_kind
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    extension        VARCHAR(16)  NOT NULL,
    media_type       VARCHAR(255) NOT NULL,
    signature_hex    VARCHAR(64),
    signature_offset INTEGER      NOT NULL DEFAULT 0,
    text_only        BOOLEAN      NOT NULL DEFAULT FALSE,
    description      VARCHAR(500),
    created_at       TIMESTAMP(0) NOT NULL,
    updated_at       TIMESTAMP(0),
    created_by       INTEGER,
    updated_by       INTEGER,
    CONSTRAINT uq_content_kind_extension UNIQUE (extension),
    CONSTRAINT fk_content_kind_created_by_user FOREIGN KEY (created_by) REFERENCES app_user (id),
    CONSTRAINT fk_content_kind_updated_by_user FOREIGN KEY (updated_by) REFERENCES app_user (id)
);
CREATE INDEX fk_content_kind_created_by_user ON content_kind (created_by);
CREATE INDEX fk_content_kind_updated_by_user ON content_kind (updated_by);

CREATE TABLE upload_policy
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id    INTEGER,
    created_at TIMESTAMP(0) NOT NULL,
    updated_at TIMESTAMP(0),
    created_by INTEGER,
    updated_by INTEGER,
    CONSTRAINT uq_upload_policy_role UNIQUE (role_id),
    CONSTRAINT fk_upload_policy_created_by_user FOREIGN KEY (created_by) REFERENCES app_user (id),
    CONSTRAINT fk_upload_policy_role FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE,
    CONSTRAINT fk_upload_policy_updated_by_user FOREIGN KEY (updated_by) REFERENCES app_user (id)
);
CREATE INDEX fk_upload_policy_created_by_user ON upload_policy (created_by);
CREATE INDEX fk_upload_policy_updated_by_user ON upload_policy (updated_by);

CREATE TABLE upload_policy_rule
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id      INTEGER     NOT NULL,
    extension      VARCHAR(16) NOT NULL,
    max_size_bytes BIGINT      NOT NULL,
    CONSTRAINT uq_upload_policy_rule UNIQUE (policy_id, extension),
    CONSTRAINT fk_upload_policy_rule_policy FOREIGN KEY (policy_id) REFERENCES upload_policy (id) ON DELETE CASCADE
);

-- ------------------------------------------------------------------ API keys

CREATE TABLE api_key
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_id       VARCHAR(32)  NOT NULL,
    secret_hash  VARCHAR(64)  NOT NULL,
    title        VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    enabled      INTEGER      NOT NULL DEFAULT 1,
    expires_at   TIMESTAMP(0),
    revoked_at   TIMESTAMP(0),
    last_used_at TIMESTAMP(0),
    created_at   TIMESTAMP(0) NOT NULL,
    updated_at   TIMESTAMP(0),
    created_by   INTEGER      NOT NULL,
    updated_by   INTEGER,
    CONSTRAINT uq_api_key_key_id UNIQUE (key_id),
    CONSTRAINT fk_api_key_created_by_user FOREIGN KEY (created_by) REFERENCES app_user (id),
    CONSTRAINT fk_api_key_updated_by_user FOREIGN KEY (updated_by) REFERENCES app_user (id)
);
CREATE INDEX fk_api_key_created_by_user ON api_key (created_by);
CREATE INDEX fk_api_key_updated_by_user ON api_key (updated_by);

CREATE TABLE api_key_folder
(
    api_key_id INTEGER     NOT NULL,
    folder_id  INTEGER     NOT NULL,
    permission VARCHAR(10) NOT NULL DEFAULT 'READ',
    PRIMARY KEY (api_key_id, folder_id),
    CONSTRAINT fk_api_key_folder_folder FOREIGN KEY (folder_id) REFERENCES folder (id) ON DELETE CASCADE,
    CONSTRAINT fk_api_key_folder_key FOREIGN KEY (api_key_id) REFERENCES api_key (id) ON DELETE CASCADE
);
CREATE INDEX ix_api_key_folder_key ON api_key_folder (api_key_id);
CREATE INDEX fk_api_key_folder_folder ON api_key_folder (folder_id);

-- ------------------------------------------------------------------ audit

CREATE TABLE action_history
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_name        VARCHAR(100)  NOT NULL,
    table_name         VARCHAR(100)  NOT NULL,
    entity_id          INTEGER       NOT NULL,
    action             VARCHAR(100)  NOT NULL,
    action_description VARCHAR(1000),
    description        VARCHAR(1000),
    user_id            INTEGER       NOT NULL,
    enabled            INTEGER       NOT NULL,
    state              INTEGER       NOT NULL,
    created_at         TIMESTAMP(0)  NOT NULL,
    CONSTRAINT fk_action_history_user_id FOREIGN KEY (user_id) REFERENCES app_user (id)
);
CREATE INDEX ix_action_history_entity ON action_history (entity_name, entity_id);
CREATE INDEX fk_action_history_user_id ON action_history (user_id);

-- ------------------------------------------------------------------ seed rows
-- Exactly what V1.0 to V2.19 leave in an empty MySQL, with the same ids. The ids are given
-- explicitly because rows refer to each other (Profiles to Home and to its tag group, the rules
-- to their policy, a folder's path to its own id), and every identity is then moved past them.
-- SchemaParityTest compares these rows with a freshly migrated MySQL's.

-- The root of the tree (V1.4) and the folder personal folders sit under (V2.11). A folder's
-- search_* columns hold SearchKey of its name (V2.16/V2_17): upper case, nothing to fold here.
INSERT INTO tag_group (id, name, title, enabled, created_at)
VALUES (1, 'profiles', 'Profiles', 1, LOCALTIMESTAMP(0));

INSERT INTO folder (id, parent_id, name, search_name, display_name, search_display_name, path, depth, kind,
                    tag_group_id, enabled, state, created_at)
VALUES (1, NULL, 'Home', 'HOME', 'Home', 'HOME', '/1/', 0, 'ROOT', NULL, 1, 0, LOCALTIMESTAMP(0)),
       (2, 1, 'Profiles', 'PROFILES', 'Profiles', 'PROFILES', '/1/2/', 1, 'PROFILES', 1, 1, 0, LOCALTIMESTAMP(0));

-- The public files page is open to anonymous visitors until an administrator closes it (V2.10).
INSERT INTO app_setting (id, setting_key, setting_value)
VALUES (1, 'public-files.anonymous', 'true');

-- The default upload policy - the one for a role without its own - and its ten kinds at 20 MB (V2.6).
INSERT INTO upload_policy (id, role_id, created_at)
VALUES (1, NULL, LOCALTIMESTAMP(0));

INSERT INTO upload_policy_rule (id, policy_id, extension, max_size_bytes)
VALUES (1, 1, 'pdf', 20971520),
       (2, 1, 'png', 20971520),
       (3, 1, 'jpg', 20971520),
       (4, 1, 'jpeg', 20971520),
       (5, 1, 'docx', 20971520),
       (6, 1, 'xlsx', 20971520),
       (7, 1, 'pptx', 20971520),
       (8, 1, 'mp4', 20971520),
       (9, 1, 'mp3', 20971520),
       (10, 1, 'txt', 20971520);

-- The permissions the MySQL migrations inserted, with their descriptions (V2.8 to V2.12, less the
-- three V2.19 removed). DataInitializer adds every other PermissionEnum constant at the first
-- start, without a description, on either database - so the catalogue ends up the same.
INSERT INTO permission (id, permission_name, description)
VALUES (1, 'REST_CREATE_FOLDER', 'Create a folder under another (explorer)'),
       (2, 'REST_RENAME_FOLDER', 'Rename a folder (explorer)'),
       (3, 'REST_DELETE_FOLDER', 'Delete an empty folder (explorer)'),
       (4, 'REST_GET_TAG_GROUPS', 'List the tag groups, for creating a category folder (explorer)'),
       (5, 'REST_MOVE_FOLDER', 'Move a folder, with everything beneath it, under another parent (explorer)'),
       (6, 'TAG_GROUP_PAGE', 'The tag groups (general tags) a top-level folder may carry (settings)'),
       (7, 'SAVE_TAG_GROUP', 'Create, rename or re-title a tag group (settings)'),
       (8, 'DELETE_TAG_GROUP', 'Delete a tag group no folder and no tag uses (settings)'),
       (9, 'GENERAL_SETTINGS_PAGE', 'The general settings page (settings)'),
       (10, 'SAVE_GENERAL_SETTINGS', 'Change a general setting (settings)'),
       (11, 'CREATE_USER_HOME', 'Create a user''s personal folder under Profiles (users)'),
       (12, 'SET_FOLDER_QUOTA', 'Set or change the quota of a folder, such as a personal folder (users)'),
       (13, 'CREATE_SHARE_LINK', 'Create a temporary share link to a file revision one may read, and revoke one''s own (files)'),
       (14, 'SHARE_LINKS_PAGE', 'The share links page: one''s own links (files)'),
       (15, 'REVOKE_SHARE_LINK', 'See and revoke every share link, not only one''s own (files)');

-- Every identity past the ids given above, or the first row the application inserts is given 1.
SELECT setval(pg_get_serial_sequence('tag_group', 'id'), (SELECT MAX(id) FROM tag_group));
SELECT setval(pg_get_serial_sequence('folder', 'id'), (SELECT MAX(id) FROM folder));
SELECT setval(pg_get_serial_sequence('app_setting', 'id'), (SELECT MAX(id) FROM app_setting));
SELECT setval(pg_get_serial_sequence('upload_policy', 'id'), (SELECT MAX(id) FROM upload_policy));
SELECT setval(pg_get_serial_sequence('upload_policy_rule', 'id'), (SELECT MAX(id) FROM upload_policy_rule));
SELECT setval(pg_get_serial_sequence('permission', 'id'), (SELECT MAX(id) FROM permission));
