-- Roadmap 9.10 step 5 (2.14.0): multipart upload on the S3 surface - what `aws s3 cp`, `sync` and
-- `rclone` switch to by themselves above 8 MB.
--
-- An upload in progress: who began it (the key, and the person it acts for), for which bucket and
-- key, with which metadata (sent with CreateMultipartUpload, as S3 takes it) and how large it may
-- grow - the smaller of the server's cap and the principal's limit for the extension, asked when it
-- began and again when it completes. Its parts wait as files in the upload temporary directory,
-- s3-multipart/{upload_id}/, each named in its row: a part sent twice is the one whose row is last
-- written, never a file another request is writing.
--
-- Completed, the parts become one file through the same path as any upload, and the rows go;
-- aborted, they go; abandoned, S3MultipartSweeper removes them after
-- filemanagement.s3-api.multipart.expire-hours. Nothing here outlives the upload.

CREATE TABLE s3_multipart_upload
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id    VARCHAR(64)    NOT NULL,
    api_key_id   INTEGER        NOT NULL,
    user_id      INTEGER        NOT NULL,
    bucket       VARCHAR(255)   NOT NULL,
    object_key   VARCHAR(1024)  NOT NULL,
    content_type VARCHAR(255),
    metadata     JSONB,
    max_bytes    BIGINT         NOT NULL,
    created_at   TIMESTAMPTZ(0) NOT NULL,
    CONSTRAINT uq_s3_multipart_upload_upload_id UNIQUE (upload_id),
    CONSTRAINT fk_s3_multipart_upload_api_key FOREIGN KEY (api_key_id) REFERENCES api_key (id) ON DELETE CASCADE,
    CONSTRAINT fk_s3_multipart_upload_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

-- A key's uploads in a bucket, in key order (ListMultipartUploads); and the oldest first (the sweep).
CREATE INDEX fk_s3_multipart_upload_api_key ON s3_multipart_upload (api_key_id, bucket, object_key, id);
CREATE INDEX fk_s3_multipart_upload_user ON s3_multipart_upload (user_id);
CREATE INDEX ix_s3_multipart_upload_created_at ON s3_multipart_upload (created_at);

CREATE TABLE s3_multipart_part
(
    upload_id   BIGINT         NOT NULL,
    part_number INTEGER        NOT NULL,
    file_name   VARCHAR(100)   NOT NULL,
    size        BIGINT         NOT NULL,
    md5         VARCHAR(32)    NOT NULL,
    created_at  TIMESTAMPTZ(0) NOT NULL,
    CONSTRAINT pk_s3_multipart_part PRIMARY KEY (upload_id, part_number),
    CONSTRAINT fk_s3_multipart_part_upload FOREIGN KEY (upload_id) REFERENCES s3_multipart_upload (id) ON DELETE CASCADE,
    CONSTRAINT ck_s3_multipart_part_number CHECK (part_number BETWEEN 1 AND 10000)
);
