-- Roadmap 12.2 and 12.3 (2.13.0): metadata - what is known about a document or a folder that its
-- bytes and its name do not say - as a JSON object.
--
--  * file_details.metadata: one document per revision, as S3 keeps user metadata per object
--    version; the file's current metadata is its newest revision's. Sent with an upload (the
--    pages, v1's `metadata` field, the S3 surface's x-amz-meta-* headers) and set later through v1
--    or the file page.
--  * folder.metadata: one document per folder, written by a person on the web or through v1 - not
--    inherited below the folder, never copied onto its files.
--
-- jsonb: any keys, no schema change for a new field, stored parsed; searched by containment
-- (metadata @> '{"contractNo":"C-5678"}') through the GIN indexes. jsonb_path_ops serves @> only,
-- smaller and faster than the default operator class, and @> is the one search there is.
--
-- A document is an object with at least one key, or there is none: NULL. The application never
-- writes '{}' (MetadataDocument), and the checks say so to anything else that writes.

ALTER TABLE file_details ADD COLUMN metadata JSONB;
ALTER TABLE file_details ADD CONSTRAINT ck_file_details_metadata
    CHECK (metadata IS NULL OR (jsonb_typeof(metadata) = 'object' AND metadata <> '{}'::jsonb));
CREATE INDEX ix_file_details_metadata ON file_details USING gin (metadata jsonb_path_ops);

ALTER TABLE folder ADD COLUMN metadata JSONB;
ALTER TABLE folder ADD CONSTRAINT ck_folder_metadata
    CHECK (metadata IS NULL OR (jsonb_typeof(metadata) = 'object' AND metadata <> '{}'::jsonb));
CREATE INDEX ix_folder_metadata ON folder USING gin (metadata jsonb_path_ops);
-- The queue of folders still to be described (12.3): a folder's children without a document, newest
-- first, read off this index a page at a time however many there are - the ERP's one per person.
CREATE INDEX ix_folder_undescribed ON folder (parent_id, created_at DESC, id DESC) WHERE metadata IS NULL;

-- Every change of a revision's metadata is a file_history event (METADATA_CHANGED) - the document
-- before and after it here: up to 16 KB each, which `detail` (1000 characters) could not hold.
-- An upload's own document is on its FILE_UPLOADED / VERSION_ADDED / FORMAT_ADDED event, as `after`.
ALTER TABLE file_history ADD COLUMN metadata_before JSONB;
ALTER TABLE file_history ADD COLUMN metadata_after JSONB;

-- A folder's changes, kept as file_history keeps a file's: the folder's id and title as they were,
-- the documents, who and with which key - and no foreign key on the folder, so the record outlives
-- it.
CREATE TABLE folder_metadata_change
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at     TIMESTAMPTZ(0) NOT NULL,
    folder_id       INTEGER        NOT NULL,
    folder_title    VARCHAR(1000),
    metadata_before JSONB,
    metadata_after  JSONB,
    user_id         INTEGER        NOT NULL,
    username        VARCHAR(150)   NOT NULL,
    api_key_id      INTEGER,
    CONSTRAINT fk_folder_metadata_change_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_folder_metadata_change_api_key FOREIGN KEY (api_key_id) REFERENCES api_key (id)
);

CREATE INDEX ix_folder_metadata_change_folder ON folder_metadata_change (folder_id, occurred_at DESC, id DESC);
CREATE INDEX fk_folder_metadata_change_user ON folder_metadata_change (user_id);
CREATE INDEX fk_folder_metadata_change_api_key ON folder_metadata_change (api_key_id);
