-- The history of every file, kept apart from the file (2.5.0).
--
-- action_history names a row by its number and says what happened in a sentence; once a file is
-- deleted nothing tells what it was, and its number could be handed to a new file (issue 98). This
-- table is one row per thing that happened to a file - who, when, with which API key, to which
-- revision, where - with everything a person reads copied in at the moment: the name, the version
-- and format, the size, the folders above it as one line, the username. No foreign key reaches the
-- file, its revisions or its folder, so deleting a file, or a folder with everything under it,
-- leaves the account of what it was and who removed it. A file is followed by its external id,
-- which is never reused. Written by FileHistoryService in the transaction of the change, never
-- updated, never deleted.
--
-- Indexed for the ways it is read, each newest first and each an index scan that stops at the
-- page: one file's history (by external id), everything (by time), one kind of event, one person's
-- and one API key's (by the foreign key, which PostgreSQL indexes only when asked), and the name
-- search - a trigram index on the folded name, as every search has had since V3.2. Measured on a
-- million events: every page under 15 ms; a rare event filtered without its index took 120 ms.

CREATE TABLE file_history
(
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at              TIMESTAMPTZ(0) NOT NULL,
    event                    VARCHAR(30)    NOT NULL,
    file_info_id             INTEGER        NOT NULL,
    file_external_id         VARCHAR(36),
    file_name                VARCHAR(100),
    search_name              VARCHAR(200),
    file_details_id          INTEGER,
    file_details_external_id VARCHAR(36),
    version                  INTEGER,
    file_extension           VARCHAR(10),
    file_size                BIGINT,
    folder_id                INTEGER,
    folder_title             VARCHAR(1000),
    detail                   VARCHAR(1000),
    user_id                  INTEGER        NOT NULL,
    username                 VARCHAR(150)   NOT NULL,
    api_key_id               INTEGER,
    CONSTRAINT fk_file_history_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_file_history_api_key FOREIGN KEY (api_key_id) REFERENCES api_key (id)
);

CREATE INDEX ix_file_history_file ON file_history (file_external_id, occurred_at DESC, id DESC);
CREATE INDEX ix_file_history_occurred_at ON file_history (occurred_at DESC, id DESC);
CREATE INDEX ix_file_history_event ON file_history (event, occurred_at DESC, id DESC);
CREATE INDEX fk_file_history_user ON file_history (user_id, occurred_at DESC, id DESC);
CREATE INDEX fk_file_history_api_key ON file_history (api_key_id, occurred_at DESC, id DESC);
CREATE INDEX ix_file_history_search_name_trgm ON file_history USING gin (search_name gin_trgm_ops);

-- ------------------------------------------------------------------ what can be known of the past
--
-- The history starts from what the database already holds, and says no more than it knows.
--
--   1. Every file there is, and every revision it has: when, by whom and with which key they were
--      made is on the rows themselves (created_at, created_by, created_by_api_key_id), exact. The
--      file's first revision, if it is of version 1, is the upload; the first revision of any
--      other version is that version added, and every other revision a format added. The folder
--      is the one the file is in now - where it was then was never recorded.
--   2. What action_history recorded about a file that is still there, after it was made: moves,
--      description changes, made public or private, share links. The file must be older than the
--      record, or the record was about a file whose number this one inherited (issue 98).
--   3. What it recorded about files that are gone: when each was made and deleted, and by whom -
--      but not its name, which action_history never held. Those rows have no external id, and
--      appear in the history of everything, not under any file.

CREATE TEMPORARY TABLE folder_titles ON COMMIT DROP AS
SELECT f.id,
       (SELECT string_agg(coalesce(nullif(btrim(a.display_name), ''), a.name), ' / ' ORDER BY a.depth)
        FROM folder a
        WHERE a.depth > 0
          AND a.id IN (SELECT segment::INTEGER
                       FROM regexp_split_to_table(f.path, '/') AS segment
                       WHERE segment <> '')) AS title
FROM folder f;

-- 1. the files and revisions there are
INSERT INTO file_history (occurred_at, event, file_info_id, file_external_id, file_name, search_name,
                          file_details_id, file_details_external_id, version, file_extension, file_size,
                          folder_id, folder_title, detail, user_id, username, api_key_id)
SELECT d.created_at,
       CASE
           WHEN d.id = first.first_id AND d.version = 1 THEN 'FILE_UPLOADED'
           WHEN d.id = (SELECT min(v.id) FROM file_details v WHERE v.file_info_id = d.file_info_id AND v.version = d.version)
               THEN 'VERSION_ADDED'
           ELSE 'FORMAT_ADDED'
       END,
       fi.id, fi.external_id, fi.file_name, replace(fi.search_name, ' ', ''),
       d.id, d.external_id, d.version, d.file_extension, d.file_size,
       fi.folder_id, t.title, NULL, d.created_by, u.username, d.created_by_api_key_id
FROM file_details d
    JOIN file_info fi ON fi.id = d.file_info_id
    JOIN (SELECT file_info_id, min(id) AS first_id FROM file_details GROUP BY file_info_id) first
        ON first.file_info_id = d.file_info_id
    JOIN app_user u ON u.id = d.created_by
    LEFT JOIN folder_titles t ON t.id = fi.folder_id;

-- ... and the upload of a file whose first version was deleted since: the file row itself
INSERT INTO file_history (occurred_at, event, file_info_id, file_external_id, file_name, search_name,
                          folder_id, folder_title, user_id, username, api_key_id)
SELECT fi.created_at, 'FILE_UPLOADED', fi.id, fi.external_id, fi.file_name, replace(fi.search_name, ' ', ''),
       fi.folder_id, t.title, fi.created_by, u.username, fi.created_by_api_key_id
FROM file_info fi
    JOIN app_user u ON u.id = fi.created_by
    LEFT JOIN folder_titles t ON t.id = fi.folder_id
WHERE NOT EXISTS (SELECT 1 FROM file_history h WHERE h.file_info_id = fi.id AND h.event = 'FILE_UPLOADED');

-- 2. what was recorded about files that are still there, after they were made
INSERT INTO file_history (occurred_at, event, file_info_id, file_external_id, file_name, search_name,
                          folder_id, folder_title, detail, user_id, username, api_key_id)
SELECT h.created_at,
       CASE
           WHEN h.action_description = 'MOVE FILE_INFO' THEN 'FILE_MOVED'
           WHEN h.action_description = 'UPDATE FILE_INFO' THEN 'DESCRIPTION_CHANGED'
           WHEN h.description LIKE '%to -1' THEN 'FILE_UNPUBLISHED'
           ELSE 'FILE_PUBLISHED'
       END,
       fi.id, fi.external_id, fi.file_name, replace(fi.search_name, ' ', ''),
       CASE WHEN h.action_description = 'MOVE FILE_INFO' THEN NULL ELSE fi.folder_id END,
       CASE WHEN h.action_description = 'MOVE FILE_INFO' THEN NULL ELSE t.title END,
       CASE
           WHEN h.action_description = 'UPDATE FILE_INFO'
               THEN left(substring(h.description FROM 'new description=(.*)$'), 1000)
           WHEN h.action_description = 'MOVE FILE_INFO' THEN left(h.description, 1000)
       END,
       h.user_id, u.username, h.api_key_id
FROM action_history h
    JOIN file_info fi ON fi.id = h.entity_id AND fi.created_at <= h.created_at
    JOIN app_user u ON u.id = h.user_id
    LEFT JOIN folder_titles t ON t.id = fi.folder_id
WHERE h.entity_name = 'FileInfo'
  AND h.action_description IN ('MOVE FILE_INFO', 'UPDATE FILE_INFO', 'CHANGE STATE FILE_INFO');

INSERT INTO file_history (occurred_at, event, file_info_id, file_external_id, file_name, search_name,
                          file_details_id, file_details_external_id, version, file_extension, file_size,
                          folder_id, folder_title, detail, user_id, username, api_key_id)
SELECT h.created_at,
       CASE
           WHEN h.entity_name = 'FileShareLink' THEN 'SHARE_LINK_CREATED'
           WHEN h.description LIKE '%to -1' THEN 'REVISION_UNPUBLISHED'
           ELSE 'REVISION_PUBLISHED'
       END,
       fi.id, fi.external_id, fi.file_name, replace(fi.search_name, ' ', ''),
       d.id, d.external_id, d.version, d.file_extension, d.file_size,
       fi.folder_id, t.title, NULL, h.user_id, u.username, h.api_key_id
FROM action_history h
    JOIN file_details d ON d.id = CASE
                                      WHEN h.entity_name = 'FileDetails' THEN h.entity_id
                                      ELSE substring(h.description FROM 'to fileDetails id=([0-9]+)')::INTEGER
                                  END
                       AND d.created_at <= h.created_at
    JOIN file_info fi ON fi.id = d.file_info_id
    JOIN app_user u ON u.id = h.user_id
    LEFT JOIN folder_titles t ON t.id = fi.folder_id
WHERE (h.entity_name = 'FileDetails' AND h.action_description = 'CHANGE STATE FILE_DETAILS')
   OR (h.entity_name = 'FileShareLink' AND h.action_description = 'CREATE SHARE LINK');

-- 3. files that are gone: made and deleted, by whom, but nameless
INSERT INTO file_history (occurred_at, event, file_info_id, user_id, username, api_key_id)
SELECT h.created_at,
       CASE WHEN h.action = 'CREATE' THEN 'FILE_UPLOADED' ELSE 'FILE_DELETED' END,
       h.entity_id, h.user_id, u.username, h.api_key_id
FROM action_history h
    JOIN app_user u ON u.id = h.user_id
WHERE h.entity_name = 'FileInfo'
  AND h.action IN ('CREATE', 'DELETE')
  AND NOT EXISTS (SELECT 1 FROM file_info fi WHERE fi.id = h.entity_id AND fi.created_at <= h.created_at);
