-- Who downloaded which file, when, and from which address (2.7.0).
--
-- One row per download - a person signed in, an API key, a share link, or nobody at all on the
-- public files - with the address it came from, so a file can be answered for with or without a
-- user behind it. What a person reads is copied in at the moment: the file's name, the revision's
-- version, the username. No foreign key reaches anything: a download outlives the file, the
-- revision, the share link and the folder it concerned, and the row is written on a connection of
-- its own, apart from any request's transaction (DownloadRecorder). Never updated; removed only by
-- age, filemanagement.downloads.retention-days after it happened (DownloadRetention).
--
-- Kept out of file_history on purpose: a download is the commonest thing that happens to a file,
-- tens of times the changes, and its rows are a quarter the size. Its own table keeps the history's
-- pages as fast as they are and lets the downloads be kept for a period of their own.
--
-- Indexed for the ways it is read, each newest first and each an index scan that stops at the page:
-- everything (by time - also what the retention deletes by), one file, one person, one API key, one
-- address. Not one downloaded revision: a file's page lists all of its revisions' downloads.

CREATE TABLE file_download
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at     TIMESTAMPTZ(0) NOT NULL,
    channel         VARCHAR(12)    NOT NULL,
    file_info_id    INTEGER        NOT NULL,
    file_details_id INTEGER        NOT NULL,
    file_name       VARCHAR(255)   NOT NULL,
    version         INTEGER,
    folder_id       INTEGER,
    user_id         INTEGER,
    username        VARCHAR(150),
    api_key_id      INTEGER,
    share_link_id   INTEGER,
    client_ip       VARCHAR(45)
);

CREATE INDEX ix_file_download_occurred_at ON file_download (occurred_at DESC, id DESC);
CREATE INDEX ix_file_download_file ON file_download (file_info_id, occurred_at DESC, id DESC);
CREATE INDEX ix_file_download_user ON file_download (user_id, occurred_at DESC, id DESC) WHERE user_id IS NOT NULL;
CREATE INDEX ix_file_download_api_key ON file_download (api_key_id, occurred_at DESC, id DESC) WHERE api_key_id IS NOT NULL;
CREATE INDEX ix_file_download_client_ip ON file_download (client_ip, occurred_at DESC, id DESC) WHERE client_ip IS NOT NULL;
